---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airbyte-api
  namespace: maxdl-orchestrate
spec:
  encryptedData:
    AIRBYTE_CLIENT_ID: AgCCgQF3onRpyF8ZSVwXbNqoUNCc14t0ywFJkEDuqrTOTu7JgXGjBoSLOP4Umk2HqccCIs/kjD8lYSZvk93CAXOoCtOkOcjMyYgvCmWH9EPk/OZeLaHQcVP4iJ/9aJQqfGDwINF4m6qLDFDE5OiQ77C84VAJb6xmnPA4zOOR6cjQ4+fjEk25gR2BFhncf8yqRN25LSTGNF+LAoV/jWXc9ggmLQTJh9Zf04uAzhUodDMwfvgdZ/v/xriA4NsB89J0HcXqt0wLY/t5hpApr78j4RwpRWKJ8N8nnuTSgSsHV66xTYIOnmJfa2lErccL6wbO6Me2TIGQuPU0WgVMcENwjDm/I61hJ+eFfQ+nWaE/P1cYhs51en9zHZm9JYeV/Hwn0nzl4G4eyc7M5ZEzkUJefb6DySRflttx/eYrs22NoNNefEO2QLU7BKwDRLg/GO2AIPp7ZZzEG81lojR93AXAH4kWl3mnJ6y9XuDTB4OMkCyHec7z0xTmYzwGftI/MA4nxcXzf0f80zIbrh+5Xczta4rD5CX+AeGvEU+vFnS/PhwvKzzMo9ZdjPmndr7D+D3K3Aizt4k3i58iyxaapjk/uoh9vRJJvAhXDN9gN0Y7LhSw4cNtNEQ3ChJzGH8IvAoxY7oIIeB3gasaorZYRW+rSnUliNnNhSBHwjyZK+5Gjfy3LtkX5wM46Mv5A70dRgK92ewlxe4VZyIrMt256jv+bvmBj1vQy/0yBRMS3QiR30uph36q4Fk=
    AIRBYTE_CLIENT_SECRET: AgAnlh91MiVstdZ6+DDGoMGlTlpwCcuFEB5zl17UjLbmKY8uD0ZFnKRmB4rAD4lAVOUxuvSIF/d1ike1UigEChCJIDcOxKaJaz232kpYPNa1f7+YE19QsdOSbQCuJZjFo8gb3V5O/pi66zYItzfQjOgr9Ad5JVMx9qylJZZ2iKQ76hFZ76hUagf4UUcnPv251CUG6lbUf/dFshXv4EKCpK6RtoAjD7xDVwU5Pg6N6b5BVJif5x/HzkqyINghdNrt3uqz6ogd9cYlrktEFwusGdQXXBZBlEBmG9S3F+Svb5xSBv1GKkugWQaKb7ouVrfFNcODWcVJoG4mNEoJTGJS0+DGHvvd0XrYQSwLlTzxrcXwB+vTkumhtDGXhfWROadqczPOgK2Mkw2LN1uFjAlO7eUrMOcLYfxR+l2Izh747eTxxeKhWPkpW0SvY/pmoXptT0popLP8zMMudx9/KnRW4fx8Vyz9g+eiNl9/g4cw9wjj4k0OSvI6MswR2zHvwTdyyooHcYElx8DNxW1lvZD26WR09qGaLBTaZJ/FrJ6/pbOZNczGmtoThD0hRgR75XeGvvMIZ80dKCE6HgeM9d8PHzSg4+dDuySNjvQ4QiS4qJ6O0tkctrTvfnd+bIa8Uohdck9y8NdhLyFaXhDZGKyf2WX4/wboJVQEiV08zjT/HvwweL4Bu+sgUmoBEEF6gP36SGp25KmjcAQ6ViR5Ub63jR6/rqq9ToAjsE7M+IfvSLUw2Q==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: maxdl
      name: airbyte-api
      namespace: maxdl-orchestrate
    type: Opaque
