---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-secrets
  namespace: maxdl-governance
spec:
  encryptedData:
    openmetadata-airflow-password: AgADyOLIFvgphsOXKg5rFH8oQ8/MVgTs1bnepeRVTAJLire5yBHOZbSQsRDRal3nkiP2VFowrkji7rDv8oHDA0BoG+Omu/ZL3fLI/mAXS05Ap2L1jMicQgdTp0EVCOG8jZtUi0pPLOcAphRMllXBWXGkgS6ggyze80ku36oDDvBtipdxlTRC7+BrQE35UmXxsRd1pY+6qMhV9k/nbkVFlYelZ0N3iaLI6V0g28yOrGAukTc4XJ/l9t6ej27OqaMGlEyWBdUUVFzBond2kieydY6DdTWm3dK1jU69W2EzoRXj+Aa88FAeAgF0F5ScBjvXfGBfwtavbCkbftqOsflLBgu2Y2Izdc/M1kdyh4n9QK/TFxwb5JnoaDWD71XrzvIjP/AjNQScQMEsk6fxx+eCGGfzdTl2NKHKZllmXScU2ZuwMmded6OVKk6Ia/U43/y5Vip8Dwmd0Amkz3Guf8gAVUzBoyMiq6+f2oVig6xtev70Ld2wWy+Omgozsr2smTh8bJI4e6Y5mg3iF/EbEYHgFDUE2OkmxBP7VjG6C/g3r8jGMVUFqFVN+pwMUlAnskzvxqrQiL2lcup8jhEGLL7wvn3aCj0/qBQTKybJ52pYJh2YO7MHby5svyudul+5radxxbaRoE8B8kwzt3K4DPVnl6oGIdsMzPac63O8+lZDO8m1nTz3WdDt7FivU+2ss2tMEeRJ9m6sNQ==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: maxdl
      name: airflow-secrets
      namespace: maxdl-governance
    type: Opaque
