---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-webserver-secret
  namespace: maxdl-orchestrate
spec:
  encryptedData:
    webserver-secret-key: AgCV0SQPFdT77+/3AweNhJ7z9Zrav/OXWW7pTI1qHkuQjpSR+kf4m03qYlhKDoYibWDvV5nS8w52nVs4GutvCNk8l/nFKdVOpYxlzCrbIJ0zjEcOBi9BbKewRTvLJEkZ+VFtBA37oYalJg5cn1k/iAH8lGq5Mjbo+19Vw+bkJLZKraEXEKkbxFfVvPomA1mOAIfnM84sRUDoCP0LAsLbEsnnh2hG0LAsmT2sQIAjrtFnFKfSDQOcg8UJf/yyBq/7f4iw06bzWfDtH8fdc4B04g8yFu6Ax9sRT/ymjw6xhiBv4W+UjC1oQrp+DR5E5616OgjqwmwjoxTR+BU+Fwx9MXCMlO3hVIsnAKBSQ2U6YMjjLRpEEXSSrUH9DQcDxVvS4Y961vlxm1JofJ4q+ByTwkF9cpFSHfNDf60pAMn3kx+mhgm5lNjD838OVl/Bdct98mP3tOEp67dWR6nSoXkhUG1rVmFdpoMrVJqYVqF/mPOKo2kD3+m4mZwX+7Aq6ADQt1Wyghi+T9h3Y61py0Xyxr5rppthWY5uBrEPgLB7Je2P+LUCGXBw/lTqJKxYnWfJyrVBrlYssr19C9ueq8waCr6L//OnIuTkKR8uLQiiFz41pWixWSNiMgy143JZxN2B6ocw6lh0w5emeFRLDZTFDTb7Dy2yEDFIR7MvcfHWK445eYvP0FdED9jeeZQFnaXGi41pAB4DBOHaPw2zDxbnU73Wns6nNAj40YE/ZjQfojvnvaEQ834VK6fbjRV/S6UWmveqb5YI9kSEYQ==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: maxdl
      name: airflow-webserver-secret
      namespace: maxdl-orchestrate
    type: Opaque
