---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-secrets
  namespace: maxdl-governance
spec:
  encryptedData:
    openmetadata-mysql-password: AgB1x1LQmwFess8w4DLqsnsn5DLjCs1lgaF+wkX49bURKL4Js0X/nqxPlogKRPLjcDrHRtRe+yDmiOwyuwgd28I+8a+r7MlDekUSB+Ah4E6qfFlHDbXki6GkaR1tvRUKNwQ0+WGbIK2EcOceEGEa5QR8Gl9WNxWFk9/CLw4p+QhIk0+gZlCZl/TkSZ+HQ1b6XzDyHoa/6knh+mS8FCK64Qp/Kr4y5kj/0ZeVZ2wmrY4evxGtgTLXhzLvy+ioQnucXA45MHy6sirLlHWs6iJqgeHwXIeYLEqnD1L5zmE3z/uo/o65JJSzkoDqpAYgsaZPuY/xMI6mpExLpoONO1WoOa1jGwaCL051uf8PjiiV0BO5HbKSTSR2VhOa8ZWmlbfsNMkCMMgAHfi1nThiJCaPbX7/ROVq/gjmMgap6o7yfKQJLumk9huWDskH+WmtUeX+KFZuo3jv9mH/xH5ozEEz3wJrSeM4Ars5thHUwRsF2dm+V/9BjqTAiTJ98DWkzGO3mfy+j+gseQYc0g56Xk9eMYE0xcfhKIKps0ApcEiqjxDs1FAErwoBva169SI8+xsQJRLzO2LXl+AK13FprFzX/Ninto+9lilEn831bqf7ouly6Wwvlvhe5EyGxsbHtjIr39vGUpvuuWtOWBpUqbKEbXBc8vEus59RORJFeOEuFSlTI59Q3S/ezpxGTCwM9j6gOntBWB+0rK7ZH8EdJODGDh60PAesIIU=
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: maxdl
      name: mysql-secrets
      namespace: maxdl-governance
    type: Opaque
