---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: superset-secret
  namespace: maxdl-bi
spec:
  encryptedData:
    SUPERSET_SECRET_KEY: AgCXCZ4ETcvnGkfpxrCHiABZf+SYduauxsUJmFD7J/tNf2h6BT+2nMz1TVAQaB9hexCpEcn49Xaw4wjSa9bVGeqK9Pq9vUP4FPFbkEliK7KNDUuFiQc/JesgLtzQ9jJH51MY+Q/83FCyUJUuN7/etjiO0blpvIbNaRMTO+To9ujnhE6NU/GtKpk9NFAfe/59E+EFQm92FJgPGqjRm6dMPkWoZRoQPzdXe/6CGJejYxKN/ZCMN3QnQmEPQblgcAukv2bbsHFO0owDm21sC6tXpNKv1lxGTdbHB4h4DC+0wUIkB5qmug8TFgk0ZFUDOxlXsUhuH9mkQSpeyoHUjZ+YOVsukWmY+YyHk/14GtvMjQ8HhHrMXjbpLmbFRKj7C8cwjMRNYYz7Rw8eAubAHkWsBGIIvbreR7WSIMgfNnnG9UDr2fMfb8Iixj+h4DzmfPVcxeCBPE9B1yUjAEaNQ3KDOWtsSdSK+oVEwLHT1vQwowG/JrtQFzmkDFtHk6+V8tVpvWdSfIW4eI9EaZR35r6r67M16lVtotBfmxn2JE21U9x1ZuNbOwWMI89l6Wf03UEoBIdYiiejrlVxx2nlvH+IVTEmwmFr81tn9IFkJ3Z2VWKBc1EPhvL8jwU4cmZlyD7u27x/5WwztMrFrYiwHXgJHvQV4A1+W42ODEcUyiZKGDsP3RZOHDrRqqmqtW7xalZOE1d0HBVDgXItlB4e5us7k1FMHs6PvXZjzYQ/L4YkOSzkqfE1nWzlwbgCPbf0KOk9aGjz/2OmqVVxPA==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: maxdl
      name: superset-secret
      namespace: maxdl-bi
    type: Opaque
