---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: trino-password-db
  namespace: maxdl-query
spec:
  encryptedData:
    password.db: AgAja6q1IDcZBdIysLk31qKwWxfa6iK8ok/YxnUophsHx3W9JtnHcle9WQ3zM2OcHvQum+us2hngcP1kQDzsTuK8fWN7iP19VBBnTtLfzoOcMHa2ihJXNz34qK/HHOQmO1nRuyH1GV7/1DIsd4vYIBXohI6yNACgVb/q8q6HtrS9/5bMQJqN5WhCQvBxSVQ4IrB+sJ8L9BfF1wKQ3Kc8vITdQ7MKOGBAp3SGh81ZQ1sUFQy43SVvEe0CYO/wcwPqtmbzYgZZLY5bK6U9azY94Fj3PLWur/s0XNChwNLOcRjX95QM9T+6sJRsqiiT0CDqZj0Hjwu4BBVgEqPiy88yxEtn67g+Muw937LMSgYsGNZFuUuQUhve/xWQXfzxEyau38iSu524Y96TxDoidB9VigyEhffqnEPlXdK08npxs2GuiT6GQTA+wdsy50+C2L7Ju3EKoV42QJMuxOfoCI4c+cH9aTWvveABW0Q3pry7TSZTcJ4kywwnujH4DDD79jIFKdsD8nrpWWSt4ZZCY5p/hh6A4hSu4JuUQI8wD1ergLd+2cchcH2nteNRRMnoZLXPhHPvk3OKNYse5OCE7WqRaWEwim3c+SFj/X8aIG6vx6MoJiVQhyN26wdhb3aegDsTJ0G5qexzRjiormeRVX+pA58Ap6EPNUyzRkNAue+L1ZoDk8fWme6RKC+Vbop7iPy8Fw5WdMTGK4iS4QStRCWSS2vdT8XUReFNTWiVXhmcPYwMhI+FfDGADI9SSQpRGkNKrQy1G8XiocRBWNxMWnPTL9Bf+xRjfyC7ks7gNnUkp2KHbRmi4LyvzgwD7jFtSc7ncwlgiMS4Zq/ziaTiQGLowMwxthTLunM2Y/zTu/TXFuX9V68ASe48K4ZOvIxc4213
  template:
    metadata:
      name: trino-password-db
      namespace: maxdl-query
    type: Opaque
