---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: trino-password-db
  namespace: maxdl-query
spec:
  encryptedData:
    password.db: AgBcHx+AI2BVZ7+liO59gFmsH5uuy49wgKjJtEjcX0+tMhSq3L0JxzxVNjV9Br6o9HpcWy5VJXnEvaHFLGoTgIYWbHo0taOxlQZYvt+1Sm/F9g6MZieJH/rg5gwxoBHv2DOa8iUSixDWFIJw3H91QM5+2LU9G5jNu0jWIQ2NrIHxqFllahhybXx2yNKK7mANTYNKE2CzisBIyg08Qsrwl1LxgWn1baGqUMuVJDfXkdlS8mxBGH/+157d5WLeeVcYSjDQDZrYijmtK9M+z2ENwHlb4UtF9VHdoANYaj599X4WO7FeAxNfhph4VVgU504B5x4cXtIBSFvmNryiC1nC/MFPReM5P6GKK7B8z5gjlBrKaME62SJw7mx0YPTpo9y9tj4zzFnUB1QRwlaSoKRHynoTepyXlvRxbRZ10KtCrORRxOiLgEf2p/KDlfZqr7Vc1dCK2ixPFvAxGJYHkuFncxF0jgWLgAE9O0kN/fTVSQWxS4JAl+Mn1d8X6XklKP3bZYNWYId3TPZpse/5a8QkUDKctbaGNvaS2pfKUGgGRRpfnqofB+1a4F+XZGuDeKCF+bTBZt05R32zXAr7aZUj20P5+i+4ozmJG5xhVOx1vyYoBkGCefAvStG9/QEqSECnLQtg1yNcOqR9i8wVEMxGbgzr2X5QDky6E0w1cX7HaZRvk1eGYBrvyK5nDJzpjKz2wQUJ/zyvQ4zYDpTggFs8KC2Dc8usu3L0A0DwK/hRwVRuuu5yLc0IJsClydNmVHkmBfwYduJ33SCIvpLOlZM1m6YPO1XRbg==
  template:
    metadata:
      name: trino-password-db
      namespace: maxdl-query
    type: Opaque
