---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: trino-password-db
  namespace: maxdl-query
spec:
  encryptedData:
    password.db: AgARrQPpBdL3/JGM7VvESCO+r7Vk04NJtDa2Hu2HE5wj4Ft+a7kjGn8bJ9QetalCo4aInCp+xhmdNf5wyEV0VfTtUjtZsLrcB4ABfdY+s+0MllI2xzPiTUM9Rn8zoJSXokqwIVncqZhkoyqJPfese/wQiDlCsmoZwNTNzLHq/LQkjwR+2hkQa3eKfWzIbm9DcREMEMLPDaCFoO9PcagWELFmDAiv/zrNe0j5OVMn8biUI2DGPEH79z+9nDX32q+IJ5mo8CGz8HSW3UsucdpJN1dtpDrQNJW+RRfKZqF10VYbjqlDjL6M0bmKW+E1LYDV1RoAyrRtG5GsZix0/jiZvc3NMAwySdCQoCbHVfZAlt9w1ttGozXd9ydFurFr7KH6ii97JWMa9xCUbDaKr7onH+Ggcnv5tnGMw4LHRDNm6SMXEMqUGoridQ9CEbsazPN4sOSXwK4GccQI41H5MmQjnbaK3TEraGsiDjzvr7bASQrRHtcY6mJD2YGUQhqj/VSKcNsQf8cVpsJ0twxzOZyAFjP8kA2kBdmkAVum+xziaN5l4mkfE8gqC+E2dp47d5aUrvr9yia0qMOnNOj+WDmcLzCvgSRbBWe0C62pXwGJgUCHtU73YV8H8Z4GOVwJmPSPgmHxImZYobiBAfSqiAR0RQB3J4gyiAPNul623H0Lj/OWIktwpDdYcABhZ6JzEwkTQFt07Pf9WKW+KKF78kj6f+AVFAaV9/kOwLs//tByEMTsikdVuaeyxU+OE+Tp0yKOEiUcPCJFen+J6xbjzvcAra8xYAsGECQtRPMiRCmal3JqUTkocTmvJrpQjALOn9pH8UO74yk8cp6qWyduk3nJk3Pm8TMkEalW1TB8DQsh6YZYDxpmX3CGvQRO1F+WEtBG
  template:
    metadata:
      name: trino-password-db
      namespace: maxdl-query
    type: Opaque
